development:
  # secret_key_base: super_long_secret_key_for_development
  google_client_id: "393066815434-qhjulisvvhiq6mpnmg63tsn75m769h24.apps.googleusercontent.com"
  google_client_secret: "t0zc7_45oxJwFDzVvalq2Khn"